### ISSUE TITLE
self.current_rates is None causing crash

### ISSUE THREAD

**Issue by curlycrypto184** [stakewithus/oracle-voter#1]
----------PreVotes ---------
1. [FA934A3E400339A4841B17C0991BFD4104701CB544657C4803DAB90290212B7F]
-- Msgs
-- Hash 5a5657de893bd35e6cb24c539b721f801b60a6ae Denom: ukrw Salt: a78e
-- Hash b3a5c488b2d05d52b6da97700416dfee1efaf614 Denom: umnt Salt: 33bf
-- Hash 12042d5ff9c77943e9e890f03b25ffda04a4d86b Denom: usdr Salt: 2716
-- Hash 50ce277c14faba94505a883160c862d881ee20d0 Denom: uusd Salt: b383
-- Result: True Height: 151476
2. [F55B9573405BC7A40B45FFE8D775B2E4045A5E66D8117A856CC7B4ACC05DF675]
-- Msgs
-- Hash 4d9ba8332e22db979b348802c4f61c126fb2353d Denom: ukrw Salt: 24ad
-- Hash 47a910555b44f0a4239022d8b66c13e6518eabcc Denom: umnt Salt: 783a
-- Hash e9be2700acf05e8aa9137c02525425c599659590 Denom: usdr Salt: 6296
-- Hash df8885da9b3f09c48fbb441fdd33204724bba5f4 Denom: uusd Salt: d7f4
-- Result: True Height: 151481
3. [D6681C35E1EE80671F29749DF40E08C4CBCC837672DB64CCE926C313D885F8C7]
-- Msgs
-- Hash d55d69717f7eb9c535b7f28f7b499c0eb777b8ef Denom: ukrw Salt: a3ce
-- Hash f80aa0127a973c34198e68436e1d4502ede70d7b Denom: umnt Salt: cacf
-- Hash 2c44e3a665937dc8abb37e1daefcb785ef416776 Denom: usdr Salt: ab62
-- Hash 1d949130ea230360cc7ff7e77b056a232efcfb81 Denom: uusd Salt: da78
-- Result: True Height: 151486
----------(151490)---------

Traceback (most recent call last):
  File "main.py", line 72, in <module>
    handle_args(arguments)
  File "main.py", line 67, in handle_args
    cmds[cmd_key](args)
  File "main.py", line 56, in start
    loop.run_until_complete(start_coro(args))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "main.py", line 50, in start_coro
    await oracle.retrieve_height()
  File "/go/src/github.com/oraclevoter/oracle-voter/oracle-voter/oracle/machine2.py", line 79, in retrieve_height
    await self.new_height(int(current_height))
  File "/go/src/github.com/oraclevoter/oracle-voter/oracle-voter/oracle/machine2.py", line 381, in new_height
    await self.new_vote_period()
  File "/go/src/github.com/oraclevoter/oracle-voter/oracle-voter/oracle/machine2.py", line 433, in new_vote_period
    await self.append_prevote_msg("ukrw")
  File "/go/src/github.com/oraclevoter/oracle-voter/oracle-voter/oracle/machine2.py", line 170, in append_prevote_msg
    rate_row["amount"] for rate_row in self.current_rates if
TypeError: 'NoneType' object is not iterable

**Comment by olwee** [comment]
Will look into this later thanks
