### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by joe-bowman** [stakewithus/oracle-voter#15]
```
Traceback (most recent call last):
  File "oracle-voter/main.py", line 128, in <module>
    main()
  File "oracle-voter/main.py", line 124, in main
    loop.run_until_complete(start_coro(pargs))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "oracle-voter/main.py", line 41, in start_coro
    await oracle.retrieve_height()
  File "/opt/validators/terra/oracle-voter/oracle-voter/oracle/machine2.py", line 82, in retrieve_height
    block_meta = raw_res["block_meta"]
TypeError: 'NoneType' object is not subscriptable
```

All http calls should be _expected_ to fail, so there should be adequate error handling in place to catch and try again (or just do nothing for this loop).

**Comment by olwee** [comment]
Thanks for raising this, will have a look
