### ISSUE TITLE
TypeError: unhashable type: 'dict' causing crash

### ISSUE THREAD

**Issue by curlycrypto184** [stakewithus/oracle-voter#3]
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    handle_args(arguments)
  File "main.py", line 59, in handle_args
    cmds[cmd_key](args)
  File "main.py", line 48, in start
    loop.run_until_complete(start_coro(args))
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
    return future.result()
  File "main.py", line 42, in start_coro
    await oracle.retrieve_height()
  File "/opt/oracle-voter/oracle-voter/oracle/machine2.py", line 73, in retrieve_height
    await self.new_height(int(current_height))
  File "/opt/oracle-voter/oracle-voter/oracle/machine2.py", line 317, in new_height
    await self.check_txs(height)
  File "/opt/oracle-voter/oracle-voter/oracle/machine2.py", line 312, in check_txs
    self.hist_prevotes.pop(head, None)
TypeError: unhashable type: 'dict'

**Comment by olwee** [comment]
Will have a look

**Comment by olwee** [comment]
Not able to replicate, will close the issue
